### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by HEKnTEKn** [thebear132/MTG-To-XMage#1]
Hello. I receive this error when trying to run the script.

```
C:\Desktop\MTG-To-XMage-main\MTG-To-XMage-main>python program.py -moxfield imHEKnTEKn
C:\Desktop\MTG-To-XMage-main\MTG-To-XMage-main\program.py:179: SyntaxWarning: invalid escape sequence '\/'
  deckName = "".join(i for i in deckName if i not in "\/:*?<>|")
C:\Desktop\MTG-To-XMage-main\MTG-To-XMage-main\program.py:565: SyntaxWarning: invalid escape sequence '\('
  mainboard = re.findall('([0-9]{1,2}) (.*) \(([0-9a-zA-Z]{1,6})\) ([0-9]{1,4})', mainboardHTML)
C:\Desktop\MTG-To-XMage-main\MTG-To-XMage-main\program.py:566: SyntaxWarning: invalid escape sequence '\('
  sideboard = re.findall('([0-9]{1,2}) (.*) \(([0-9a-zA-Z]{1,6})\) ([0-9]{1,4})', sideboardHTML)
Moxfield set
Starting Moxfield | imHEKnTEKn
Only public decks are searchable in Moxfield
Grabbing <imHEKnTEKn>'s public decks from https://api.moxfield.com/v2/users/imHEKnTEKn/decks?pageNumber=1&pageSize=99999
Traceback (most recent call last):
  File "C:\Desktop\MTG-To-XMage-main\MTG-To-XMage-main\program.py", line 707, in <module>
    main()
    ~~~~^^
  File "C:\Desktop\MTG-To-XMage-main\MTG-To-XMage-main\program.py", line 695, in main
    MoxField(config["moxfield"], config["folder"]).Download()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Desktop\MTG-To-XMage-main\MTG-To-XMage-main\program.py", line 267, in Download
    userDecks = self.__getUserDecks()
  File "C:\Desktop\MTG-To-XMage-main\MTG-To-XMage-main\program.py", line 205, in __getUserDecks
    j = json.loads(r.text)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.496.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.496.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.496.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 363, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

C:\Desktop\MTG-To-XMage-main\MTG-To-XMage-main>pause
Press any key to continue . . .
```

Do you have any idea what might be causing this?

**Comment by StianOby** [comment]
I'm seeing this too on Windows. 

Thought it was just something local, since I had it working on my Linux desktop a week or so ago, but am now trying to run the script on my Windows laptop. But perhaps something has changed on Moxfield's side causing this error?

**Comment by HEKnTEKn** [comment]
Possible that it's an API issue, but I think I got a similar error when running for my archidekt as well.. unsure..!

**Comment by thebear132** [comment]
Yep. They sometimes update their API to combat the scraping. If i fix it i will let you guys know

**Comment by StianOby** [comment]
Great. Hope you find the time to fix it. There does not seem to be any other practical way of exporting decks from Moxfield to xMage with correct printings.

**Comment by StianOby** [comment]
PS: I have now added a relevant feature suggestion on Moxfield, feel free to upvote: https://moxfield.nolt.io/1779

(sorry for the double post)

**Comment by thebear132** [comment]
A fix is on the way. I thought they changed their API to require authentication, but there is a workaround which a little similar to the previous approach

**Comment by thebear132** [comment]
This issue has been fixed in #2, remember to also install selenium as this is the new way to fetch from the Moxfield API (see README)
`pip install selenium --break-system-packages`
